server:
  port: 8080
#  port: ${PORT:8080}
#  servlet:
#    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'

springdoc:
  swagger-ui:
    disable-swagger-default-url: 'true'
    path: '/swagger-ui'

spring:
  profiles:
    active: h2
  mustache:
    check-template-location: false

logging:
  level:
    ru.docnemo.granitis: DEBUG
    com.vaadin: DEBUG

vaadin:
  launch-browser: false

